"""
CompiledPolicy — compile a trained TileField into a zero-dependency lookup.

The tile field is the TRAINING algorithm; the compiled policy is the DEPLOYED artifact.
Learn with simulation, deploy with O(1) lookups.
"""

from zeroclaw.games import TicTacToe


class CompiledPolicy:
    """A compiled tile policy that uses pure dictionary lookup.

    Usage:
        field = TileField()
        field.train(TicTacToe(), num_games=500)
        policy = CompiledPolicy.from_tile_field(field)
        action = policy("X O  X   ")  # returns best move as str
    """

    def __init__(self, lookup: dict[str, str]):
        self._lookup = lookup
        self._boards = list(lookup.keys())

    def __call__(self, board_str: str) -> str:
        """Given a board state string, return the best action."""
        if board_str in self._lookup:
            return self._lookup[board_str]

        # Nearest-neighbor fallback (Hamming distance)
        best_dist = 999
        best_board = None
        for b in self._boards:
            if len(b) != len(board_str):
                continue
            dist = sum(1 for i in range(len(board_str)) if board_str[i] != b[i])
            if dist < best_dist:
                best_dist = dist
                best_board = b

        if best_board is not None and best_dist <= 3:
            return self._lookup[best_board]

        # Ultimate fallback: center, corners, edges
        for pos in "402681357":
            if int(pos) < len(board_str) and board_str[int(pos)] == ' ':
                return pos
        return "0"

    @classmethod
    def from_tile_field(cls, field) -> 'CompiledPolicy':
        """Compile a TileField into a deterministic lookup policy."""
        lookup = {}
        for state_str, tile in field.tiles.items():
            # Only compile states where it's X's turn
            x_count = state_str.count('X')
            o_count = state_str.count('O')
            if x_count != o_count:
                continue

            best_action = None
            best_weighted = -1.0
            for action, data in tile.items():
                visits = data["chosen"]
                wins = data["won"]
                if visits > 0:
                    empirical_wr = wins / visits
                    exploration_bonus = 0.3 / (1.0 + visits)
                    weighted = empirical_wr + exploration_bonus
                else:
                    weighted = 0.5

                if weighted > best_weighted:
                    best_weighted = weighted
                    best_action = action

            total_chosen = sum(d["chosen"] for d in tile.values())
            if total_chosen >= 1 and best_action is not None:
                lookup[state_str] = best_action

        return cls(lookup)

    def to_python(self) -> str:
        """Generate a self-contained Python source file with the compiled policy."""
        lines = [
            '"""',
            'COMPILED TILE POLICY — Zero-dependency deterministic tic-tac-toe.',
            'Generated by zeroclaw tile compiler.',
            '"""',
            '',
            '',
            'def compiled_policy(board_str):',
            '    """Given a board string, return best move index."""',
            '    _lookup = {',
        ]
        for state_str, action in sorted(self._lookup.items()):
            escaped = state_str.replace("'", "\\'")
            lines.append(f"        '{escaped}': '{action}',")
        lines.append('    }')
        lines.append('')

        lines.append('    _boards = [')
        for b in self._lookup:
            escaped = b.replace("'", "\\'")
            lines.append(f"        '{escaped}',")
        lines.append('    ]')
        lines.append('')
        lines.extend([
            '    if board_str in _lookup:',
            '        return _lookup[board_str]',
            '',
            '    best_dist = 999',
            '    best_board = None',
            '    for b in _boards:',
            '        dist = sum(1 for i in range(len(board_str)) if board_str[i] != b[i])',
            '        if dist < best_dist:',
            '            best_dist = dist',
            '            best_board = b',
            '    if best_board is not None and best_dist <= 3:',
            '        return _lookup[best_board]',
            '',
            '    for pos in "402681357":',
            '        if board_str[int(pos)] == " ":',
            '            return pos',
            '    return "0"',
            '',
        ])
        return '\n'.join(lines)

    def evaluate(self, num_games: int = 1000) -> dict:
        """Evaluate the compiled policy against random play."""
        game = TicTacToe()
        wins = 0
        draws = 0
        losses = 0

        for _ in range(num_games):
            game.reset()
            while not game.done:
                actions = game.legal_actions()
                if not actions:
                    break
                if game.current == 'X':
                    import random
                    action = self(game.state().state_str)
                    if action not in actions:
                        action = random.choice(actions)
                else:
                    import random
                    action = random.choice(actions)
                game.step(action)

            if game.winner == 'X':
                wins += 1
            elif game.winner is None or game.winner == 'draw':
                draws += 1
            else:
                losses += 1

        return {
            "wins": wins,
            "draws": draws,
            "losses": losses,
            "win_rate": wins / num_games,
            "total_games": num_games,
        }

    @property
    def size(self) -> int:
        return len(self._lookup)
